services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    working_dir: /api
  api:
    build: api
    image: rails-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    working_dir: /api
    volumes:
      - ./api:/api
      - ./api:/api/bundle
      - /api/node_modules
    env_file:
      ./api/.env
    depends_on:
      - db
  client:
    build: ./client
    image: react-client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - '3001:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    env_file:
      ./client/.env
